#!/bin/bash

clear
if [ -f /bin/vpspack ]
  then
  echo -e "\033[1;31mVpsPack \033[1;36mjá está instalado.\033[0m"
  true
  if [ -f /bin/PackSSH ]
  then
  echo -e "\033[1;31mPackSSH \033[1;36mjá está instalado.\033[0m"
  true
  fi
  if [ -f /bin/CONFVPS ]
  then
  echo -e "\033[1;31mCONFVPS \033[1;36mjá está instalado.\033[0m"
  true
  fi
  if [ -f /bin/iniciar ]
  then
  echo -e "\033[1;31mBadManager \033[1;36mjá está instalado.\033[0m"
  true
  fi
  if [ -f /bin/ajuda ]
  then
  echo -e "\033[1;31mVPSManager \033[1;36mjá está instalado.\033[0m"
  true
  fi
  if [ -f /bin/admm ]
  then
  echo -e "\033[1;31mAdmManager \033[1;36mjá está instalado.\033[0m"
  true
  fi
fi
echo " "
echo -e "\033[1;35mEscolha um dos script desejado abaixo.\033[0m"
echo -e "\033[1;36m 1\033[1;31m|\033[1;36mVpsPack
\033[1;36m 2\033[1;31m|\033[1;36mCONFVPS
\033[1;36m 3\033[1;31m|\033[1;36mPackSSH
\033[1;36m 4\033[1;31m|\033[1;36mBadManager
\033[1;36m 5\033[1;31m|\033[1;36mVPSManager
\033[1;36m 6\033[1;31m|\033[1;36mAdmManager
\033[1;36m 7\033[1;31m|\033[1;36mVoltar\033[0m"
read -p "Opção:" opcao

case $opcao in
 1)
  2031;;
 2) 
  2032;;
 3) 
  2033;;
 4)
  2034;;
 5)
  2035;;
 6)
   2036;;
 7)
   6;;
  *) 
  id > /dev/null 2> /dev/null
esac
