#!/bin/bash

clear
echo -e "\033[1;36mCONFVPS é um Script manager criado por Glemysson, \033[0m"
echo ""
echo -n -e "\033[1;31mDeseja continuar com a instalação?(s/n):\033[0m"

read resp
if [ "$resp" == "s" ]; then
   rm install
   echo ""
   clear
   echo -e "\033[1;31m Instalando, aguarde...\033[0m"
   sleep 3
   apt-get update -y
   apt-get install wget sudo -y
   wget https://raw.githubusercontent.com/glemysson-Hacker/GlEmYsSoN/master/installer.sh
   chmod +x installer.sh
   bash installer.sh
   echo " "
   tput setaf 1 ; tput bold ; read -n 1 -s -p "Pressione qualquer tecla para continuar..." ; echo "" ; echo "" ; tput sgr0
   203
elif [ "$resp" == "n" ]; then
    clear
    echo -e "\033[1;31m*     \033[1;36mInstalação cancelada.\033[0m" 
    sleep 2
    203
fi