#!/bin/bash

clear
echo -e "\033[1;36mPackSSH é um script manager criado por Mr.SSH.\033[0m"
echo ""
echo -n -e "\033[1;31mDeseja continuar com a instalação?(s/n):\033[0m"

read resp
if [ "$resp" == "s" ]; then
    echo "" 
    echo -e "\033[1;31m Instalando, aguarde...\033[0m"
    sleep 2
    rm install
    apt-get update -y 
    apt-get install wget sudo -y
    clear
    wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/InstallerPackSSH && bash InstallerPackSSH
elif [ "$resp" == "n" ]; then
    clear
    echo -e "\033[1;36m         Instalação cancelada.\033[0m" 
    sleep 2
    203
fi