#!/bin/bash

clear
echo -e "\033[1;36mBadManager é um script manager criado por BadGUY.\033[0m"
echo ""
echo -n -e "\033[1;31mDeseja continuar com a instalação?(s/n):\033[0m"

read resp
if [ "$resp" == "s" ]; then
     rm install
     echo ""
     echo -e "\033[1;31m Instalando, aguarde...\033[0m"
     sleep 3
     apt-get update -y 
     apt-get install wget sudo -y
     clear
     sudo apt-get install wget -y && wget -q https://raw.githubusercontent.com/BadGuy552/BadManager/master/instalar.sh && sudo bash instalar.sh && rm instalar.sh
    echo " "
    tput setaf 1 ; tput bold ; read -n 1 -s -p "Aperte qualquer tecla para continuar..." ; echo "" ; echo "" ; tput sgr0
    203
elif [ "$resp" == "n" ]; then
    clear
    echo -e "\033[1;31m*     \033[1;36Instalação cancelada.\033[0m" 
    sleep 2
    203
fi