#!/bin/bash

clear
echo -e "\033[1;31mAtenção! \033[1;36mEssa senha será usada para entrar no usuário atual, guardea em um lugar seguro.\033[0m" 
echo -e ""
echo -n -e "\033[1;31mDeseja continuar?(S/n):\033[0m"

read resp
if [ "$resp" == "S" ]; then
 echo ""
 tput setaf 5 ; tput bold ; read -p "Qual a nova senha para o usuário atual: " senha  ; echo "" ; echo "" ; tput sgr0
  (echo "$senha" ; echo "$senha" ) |passwd > /dev/null 2>/dev/null
  echo -e "\033[1;36mNova senha aplicada.\033[0m"
  tput setaf 1 ; tput bold ; read -n 1 -s -p "Pressione qualquer tecla para continuar..." ; echo "" ; echo "" ; tput sgr0
  2
elif [ "$resp" == "n" ]; then
    2
fi