#!/bin/bash

clear
echo -e "\033[1;31mAtenção!\033[0m \033[1;36mSe prosseguir todos os usuários, \033[1;31m(exceto o root) \033[1;36mde seu servidor serão desconectados e apagados.\033[0m"
echo " "
echo -n -e "\033[1;35mDeseja continuar?(SIM/n):\033[0m"

read resp
if [ "$resp" == "SIM" ]; then
    echo -e "\033[1;31mAguarde, removendo usuários.....\033[0m"
    for user in $(grep -v nobody /etc/passwd |awk -F : '$3 > 900 {print $1}'); do kill $(ps -u $user |awk '{print $1}'); userdel $user; done
    sleep 5
    clear 
    echo -e "\033[1;36mTodos os usuários foram removidos com sucesso :).\033[0m"
elif [ "$resp" == "n" ]; then
    2
fi
