#!/bin/bash

if [ $(id -u) -eq 0 ]
then
 clear
else
 if echo $(id) |grep sudo > /dev/null
 then
 clear
 echo "Não é root e nem tem direitos root."
 echo "Parabéns seu usuario esta no grupo sudo."
 echo -e "Para virar root execute \033[1;31msudo su\033[0m"
 exit
 else
 clear
 echo -e "Você nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
 exit
 fi
fi
function desinstalar(){
clear
echo -e "\033[1;31mATENÇÃO:\033[0m \033[1;36m Isso irá remover apenas o AdmScript, as configurações feitas com ele não serão removidas.\033[0m"
echo " "
echo -n -e "\033[1;31mDeseja continuar?(SIM/n):\033[0m"

read resp
if [ "$resp" == "SIM" ]; then
   echo -e "\033[1;36mDesinstalando o AdmScript, aguarde.\033[0m"
   	rm /bin/adm >/dev/null
        rm /bin/1 >/dev/null
        rm /bin/2 >/dev/null
        rm /bin/3 >/dev/null
        rm /bin/4 >/dev/null
        rm /bin/101 >/dev/null
        rm /bin/102 >/dev/null
        rm /bin/103 >/dev/null
        rm /bin/104 >/dev/null
        rm /bin/201 >/dev/null
        rm /bin/202 >/dev/null
        rm /bin/203 >/dev/null
        rm /bin/2031 >/dev/null
        rm /bin/2032 >/dev/null
        rm /bin/2033 >/dev/null
		rm /bin/2034 >/dev/null
		rm /bin/2035 >/dev/null
		rm /bin/2036 >/dev/null
        rm /bin/204 >/dev/null
        rm /bin/2041 >/dev/null
        rm /bin/2042 >/dev/null
        rm /bin/2043 >/dev/null
		rm /bin/2061 >/dev/null
		rm /bin/2062 >/dev/null
		rm /bin/2063 >/dev/null
		rm /bin/20342 >/dev/null
        rm /bin/205 >/dev/null
        rm /bin/206 >/dev/null
        rm /bin/207 >/dev/null
        rm /bin/207.py >/dev/null
        rm /bin/208 >/dev/null
        rm /bin/209 >/dev/null
        rm /bin/210 >/dev/null
        rm /bin/211 >/dev/null
        rm /bin/212 >/dev/null
        rm /bin/213 >/dev/null
        rm /bin/214 >/dev/null
        rm /bin/215 >/dev/null
        rm /bin/216 >/dev/null
        rm /bin/217 >/dev/null
   clear
   echo -e "\033[1;31m               Desinstalação concluída :(\033[0m"
elif [ "$resp" == "n" ]; then
    clear
    echo -e "\033[1;36m              Desinstalação cancelada :)\033[0m"
fi
} 
clear
echo " "
echo -e "\033[1;36m----¦AdmScript, created by Mr.Devim\033[0m"
echo
echo -e "\033[1;37mPara executar um comando escolha uma das opçoẽs abaixo.\033[0m"
echo -e "\033[1;31mPara sair precione Ctrl + C\033
 \033[1;36m1|Hardware
 \033[0;37m|Informações sobre o hardware desse servidor.
\033[1;36m2|Sistema
 \033[0;37m|Configuração e informações sobre o sistema desse servidor.
\033[1;36m3|Sobre
 \033[0;37m|Informações sobre o Adm Script.
\033[1;36m4|Tutorial
 \033[0;37m|Aprenda tudo e domine o AdmScript.\033[0m"
if [ -f /bin/admm ]
  then
echo -e "\033[1;36m5|AdmManager
 \033[0;37m|Iniciar o AdmManager.\033[0m" 
  true
  else
echo -e "\033[1;36m5|AdmManager
 \033[0;37m|Instalar o AdmManager.\033[0m" 
fi
echo -e "\033[1;36m6|Desinstalar
 \033[0;37m|Desinstalar o AdmScript.\033[0m"
read -p "Opção:" opcao

case $opcao in
 1)
  1;;
 2) 
  2;;
 3)
  3;;
 4)
  4;;
 5)
  if [ -f /bin/admm ]
  then
     admm
  true
  else
     wget https://raw.githubusercontent.com/Devimla/AdmManager/master/install && bash install
	fi;;
  6)
   desinstalar;;
  *)
  id > /dev/null 2> /dev/null
esac