#!/bin/bash

if [ $(id -u) -eq 0 ]
then
 clear
else
 if echo $(id) |grep sudo > /dev/null
 then
 clear
 echo "Não é root e nem tem direitos root."
 echo "Parabéns seu usuario esta no grupo sudo."
 echo -e "Para virar root execute \033[1;31msudo su\033[0m"
 exit
 else
 clear
 echo -e "Você nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
 exit
 fi
fi
function desinstalar(){
clear
echo -e "\033[1;31mATENÇÃO:\033[0m \033[1;36m Isso irá remover apenas o AdmScript, as configurações feitas com ele não serão removidas.\033[0m"
echo " "
echo -n -e "\033[1;31mDeseja continuar?(SIM/n):\033[0m"

read resp
if [ "$resp" == "SIM" ]; then
   echo -e "\033[1;36mDesinstalando o AdmScript, aguarde.\033[0m"
   rm /bin/adm
   rm /bin/1
   rm /bin/2
   rm /bin/3
   rm /bin/4
   rm /bin/101
   rm /bin/102
   rm /bin/103
   rm /bin/104
   rm /bin/201
   rm /bin/202
   rm /bin/203
   rm /bin/2031
   rm /bin/2032
   rm /bin/2033
   rm /bin/204
   rm /bin/2041
   rm /bin/2042
   rm /bin/2043
   rm /bin/2044
   rm /bin/2045
   rm /bin/205
   rm /bin/206
   rm /bin/207
   rm /bin/207.py
   rm /bin/208
   rm /bin/209
   rm /bin/210
   rm /bin/211
   rm /bin/212
   rm /bin/213
   rm /bin/214
   rm /bin/215
   rm /bin/216
   rm /bin/217
   rm /bin/218
   clear
   echo -e "\033[1;31m               Desinstalação concluída :(\033[0m"
elif [ "$resp" == "n" ]; then
    clear
    echo -e "\033[1;36m              Desinstalação cancelada :)\033[0m"
fi
} 
clear
echo " "
echo -e "\033[1;36m----¦AdmScript, created by Mr.Devim\033[0m"
echo
echo -e "\033[1;37mPara executar um comando escolha uma das opçoẽs abaixo.\033[0m"
echo -e "\033[1;31mPara sair precione Ctrl + C\033
 \033[1;36m1|Hardware
 \033[0;37m|Informações sobre o hardware desse servidor.
\033[1;36m2|Sistema
 \033[0;37m|Configuração e informações sobre o sistema desse servidor.
\033[1;36m3|Sobre
 \033[0;37m|Informações sobre o Adm Script.
\033[1;36m4|Tutorial
 \033[0;37m|Aprenda tudo e domine o AdmScript.\033[0m"
if [ -f /bin/admm ]
  then
echo -e "\033[1;36m5|AdmManager
 \033[0;37m|Iniciar o AdmManager.\033[0m" 
  true
  else
echo -e "\033[1;36m5|AdmManager
 \033[0;37m|Instalar o AdmManager.\033[0m" 
fi
echo -e "\033[1;36m6|Desinstalar
 \033[0;37m|Desinstalar o AdmScript.\033[0m"
read -p "Opção:" opcao

case $opcao in
 1)
  1;;
 2) 
  2;;
 3)
  3;;
 4)
  4;;
 5)
  if [ -f /bin/admm ]
  then
     admm
  true
  else
     wget https://raw.githubusercontent.com/Devimla/AdmManager/master/install && bash install
	fi;;
  6)
   desinstalar;;
  *)
  id > /dev/null 2> /dev/null
esac